language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
services:
 - docker
script:
 - set +e -x
 - cd ./docker
 - docker-compose down --rmi all --volumes --remove-orphans
 - docker-compose up --always-recreate-deps --force-recreate
 - cd ..
 - dotnet build
 - (cd ./test/GitLabApiClient.Test && dotnet test)
cache:
  directories:
  - $HOME/.nuget
