language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
services:
 - docker
script:
 - (cd ./docker && docker-compose up --always-recreate-deps --force-recreate)
 - dotnet build
 - (cd ./test/GitLabApiClient.Test && dotnet test)
cache:
  directories:
  - $HOME/.nuget
